version: '3.8'
services:
  cache:
    image: redis:7.0-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass "${REDIS_PASSWORD}"
    volumes: 
      - data_cache:/data
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - cache
volumes:
  data_cache: