version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      - default
    ports:
      - "5432:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migration:/migrations
    env_file: .env
    command: ["-path", "/migrations", "-database",  "$DATABASE_URL?sslmode=disable", "up"]
    networks:
      - default
    links:
      - database
    depends_on:
      - database
volumes:
  auth_data:
